# Generated by Django 2.2.16 on 2022-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
