# Generated by Django 2.2.16 on 2022-03-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220306_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='confirmationcode'),
        ),
    ]
