# Generated by Django 2.2.16 on 2022-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220307_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin'), ('moderator', 'Moderator')], max_length=100, verbose_name='роль'),
        ),
    ]
